apiVersion: batch/v1
kind: Job
metadata:
  name: anticlown-data-api-postgresql-job
spec:
  template:
    spec:
      containers:
        - name: anticlowndataapipostgresql
          image: localhost:5000/anticlowndataapipostgresql:{{TAG_NUMBER}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
      restartPolicy: Never