apiVersion: batch/v1
kind: Job
metadata:
  name: anticlown-api-postgresql-job
spec:
  template:
    spec:
      containers:
        - name: anticlownapipostgresql
          image: localhost:5000/anticlownapipostgresql:{{TAG_NUMBER}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
      restartPolicy: Never