apiVersion: batch/v1
kind: Job
metadata:
  name: anticlown-entertainment-api-postgresql-job
spec:
  template:
    spec:
      containers:
        - name: anticlownentertainmentapipostgresql
          image: {{docker_registry_domain}}/anticlownentertainmentapipostgresql:{{docker_image_version}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
      restartPolicy: Never