apiVersion: batch/v1
kind: Job
metadata:
  name: anticlown-discord-bot-postgresql-job
spec:
  template:
    spec:
      containers:
        - name: anticlowndiscordbotpostgresql
          image: {{docker_registry_domain}}/anticlowndiscordbotpostgresql:{{docker_image_version}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: PostgreSqlProduction
      restartPolicy: Never