apiVersion: apps/v1
kind: Deployment
metadata:
  name: anticlown-events-daemon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anticlowneventsdaemon
  template:
    metadata:
      labels:
        app: anticlowneventsdaemon
    spec:
      containers:
        - name: anticlowneventsdaemon
          image: {{docker_registry_domain}}/anticlowneventsdaemon:{{docker_image_version}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: TZ
              value: Asia/Yekaterinburg
