apiVersion: apps/v1
kind: Pod
metadata:
  name: anticlown-discordbot-pod-withvolume
spec:
  replicas: 1
  containers:
    - name: anticlowndiscordbot
      image: localhost:5000/anticlowndiscordbot:{{TAG_NUMBER}}
      env:
        - name: AntiClownBotFilesDirectory
          value: /settings
      volumeMounts:
        - mountPath: /settings
          name: anticlown-discordbot-settings-volume
          readOnly: false
  volumes:
    - name: anticlown-discordbot-settings-volume
      hostPath:
        path: ${AntiClownBotFilesDirectory}
        type: Directory