export enum F1DriverDto {
  Verstappen = "Verstappen",
  Perez = "Perez",
  Leclerc = "Leclerc",
  Sainz = "Sainz",
  Hamilton = "Hamilton",
  Russell = "Russell",
  Ocon = "Ocon",
  Gasly = "Gasly",
  Piastri = "Piastri",
  Norris = "Norris",
  Bottas = "Bottas",
  Zhou = "Zhou",
  Stroll = "Stroll",
  Alonso = "Alonso",
  Magnussen = "Magnussen",
  Hulkenberg = "Hulkenberg",
  Ricciardo = "Ricciardo",
  Tsunoda = "Tsunoda",
  Albon = "Albon",
  Sargeant = "Sargeant",
  Bearman = "Bearman",
  Colapinto = "Colapinto",
}
