// <auto-generated />
using System;
using AntiClown.Entertainment.Api.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AntiClown.Entertainment.Api.PostgreSqlMigrationsApplier.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.AdditionalEventsInfo.Race.Repositories.RaceDriverStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AccelerationSkill")
                        .HasColumnType("double precision");

                    b.Property<double>("BreakingSkill")
                        .HasColumnType("double precision");

                    b.Property<double>("CorneringSkill")
                        .HasColumnType("double precision");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverName");

                    b.ToTable("RaceDrivers");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.AdditionalEventsInfo.Race.Repositories.RaceTrackStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccelerationDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("BreakingDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("CorneringDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("IdealTime")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("RaceTracks");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.CommonEvents.Repositories.ActiveEventsIndex.ActiveEventsIndexStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.ToTable("ActiveEventsIndex");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.CommonEvents.Repositories.CommonEventStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CommonEvents");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.DailyEvents.Repositories.ActiveEventsIndex.DailyActiveEventsIndexStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.ToTable("ActiveDailyEventsIndex");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.DailyEvents.Repositories.DailyEventStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DailyEvents");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.F1Predictions.Repositories.Bingo.F1BingoBoardStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid[]>("Cards")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Season");

                    b.ToTable("F1BingoBoards");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.F1Predictions.Repositories.Bingo.F1BingoCardStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedRepeats")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRepeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Season");

                    b.ToTable("F1BingoCards");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.F1Predictions.Repositories.ChampionshipPredictions.F1ChampionshipPredictionStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("DriverStandings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Season");

                    b.HasIndex("UserId");

                    b.HasIndex("Season", "UserId");

                    b.ToTable("F1ChampionshipPredictions");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.F1Predictions.Repositories.ChampionshipPredictions.F1ChampionshipResultsStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Season");

                    b.ToTable("F1ChampionshipResults");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.F1Predictions.Repositories.Races.F1RaceStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSprint")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("SerializedPredictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializedResults")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("Season");

                    b.ToTable("F1PredictionsRaces");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.F1Predictions.Repositories.Results.F1PredictionResultStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DnfPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DriverPositionPoints")
                        .HasColumnType("integer");

                    b.Property<int>("FirstPlaceLeadPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SafetyCarsPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TeamMatesPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TenthPlacePoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId");

                    b.ToTable("F1PredictionsResults");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.F1Predictions.Repositories.Teams.F1PredictionTeamStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstDriver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondDriver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("F1PredictionTeams");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.MinecraftAuth.Repositories.MinecraftAccountStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("CapeUrl")
                        .HasColumnType("text");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinUrl")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsernameAndPasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.HasIndex("Username");

                    b.ToTable("MinecraftAccounts");
                });

            modelBuilder.Entity("AntiClown.Entertainment.Api.Core.Parties.Repositories.PartyStorageElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FirstFullPartyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializedParty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("FirstFullPartyAt");

                    b.ToTable("Parties");
                });
#pragma warning restore 612, 618
        }
    }
}
