name: Deploy Nginx

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_IP:
      DOCKER_REGISTRY_LOGIN:
      DOCKER_REGISTRY_PASSWORD:
      CONFIG_REPO_TOKEN:

env:
  DOCKERFILE: nginx/Dockerfile
  DOCKERIMAGE: anticlownnginx
  VALUES_FILE: values/anticlown/nginx.yaml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Docker for Insecure Registry
        env:
          DOCKER_REGISTRY_IP: ${{ secrets.DOCKER_REGISTRY_IP }}
        run: |
          sudo mkdir -p /etc/docker
          echo '{"insecure-registries": ["'$DOCKER_REGISTRY_IP'"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Log in to Docker Registry
        env:
          DOCKER_REGISTRY_IP: ${{ secrets.DOCKER_REGISTRY_IP }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_IP \
            -u $DOCKER_USERNAME --password-stdin

      - name: Build and push image
        env:
          DOCKER_REGISTRY_IP: ${{ secrets.DOCKER_REGISTRY_IP }}
        run: |
          docker build nginx \
            -f $DOCKERFILE \
            -t $DOCKER_REGISTRY_IP/$DOCKERIMAGE:${{ github.sha }}
          docker push $DOCKER_REGISTRY_IP/$DOCKERIMAGE:${{ github.sha }}

      - name: Update image tag in config repo
        env:
          CONFIG_REPO_TOKEN: ${{ secrets.CONFIG_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:$CONFIG_REPO_TOKEN@github.com/FreeeedomDive/argocd-config.git
          yq e '.image.tag = "${{ github.sha }}"' -i argocd-config/$VALUES_FILE
          git -C argocd-config config user.email "ci@github.com"
          git -C argocd-config config user.name "GitHub Actions"
          git -C argocd-config commit -am "deploy: anticlownnginx ${{ github.sha }}"
          git -C argocd-config push
