name: Deploy DataApi PostgreSql Migrator

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_DOMAIN:
      DOCKER_REGISTRY_LOGIN:
      DOCKER_REGISTRY_PASSWORD:
      CONFIG_REPO_TOKEN:

env:
  DOCKERFILE: src/DataApi/AntiClown.Data.Api.PostgreSqlMigrationsApplier/Dockerfile
  DOCKERIMAGE: anticlowndataapipostgresql
  VALUES_FILE: values/anticlown-data-api.yaml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        env:
          DOCKER_REGISTRY_DOMAIN: ${{ secrets.DOCKER_REGISTRY_DOMAIN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_DOMAIN \
            -u $DOCKER_USERNAME --password-stdin

      - name: Build and push migrator image
        env:
          DOCKER_REGISTRY_DOMAIN: ${{ secrets.DOCKER_REGISTRY_DOMAIN }}
        run: |
          docker build src \
            -f $DOCKERFILE \
            -t $DOCKER_REGISTRY_DOMAIN/$DOCKERIMAGE:${{ github.sha }}
          docker push $DOCKER_REGISTRY_DOMAIN/$DOCKERIMAGE:${{ github.sha }}

      - name: Update migrator image tag in config repo
        env:
          CONFIG_REPO_TOKEN: ${{ secrets.CONFIG_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:$CONFIG_REPO_TOKEN@github.com/FreeeedomDive/argocd-config.git
          yq e '.migration.image.tag = "${{ github.sha }}"' -i argocd-config/$VALUES_FILE
          git -C argocd-config config user.email "ci@github.com"
          git -C argocd-config config user.name "GitHub Actions"
          git -C argocd-config commit -am "deploy: anticlowndataapipostgresql ${{ github.sha }}"
          git -C argocd-config push
