name: Master Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/MasterDeployment.yml
    with:
      base-sha: ${{ github.event.before }}
    secrets: inherit
